using SponsorshipWorkflow.EntityFrameworkCore;
using Xunit;

namespace SponsorshipWorkflow.EntityFrameworkCore;

public class SponsorshipWorkflowEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SponsorshipWorkflowEntityFrameworkCoreFixture>
{

}
