using Xunit;

namespace SponsorshipWorkflow.EntityFrameworkCore;

[CollectionDefinition(SponsorshipWorkflowTestConsts.CollectionDefinitionName)]
public class SponsorshipWorkflowEntityFrameworkCoreCollection : ICollectionFixture<SponsorshipWorkflowEntityFrameworkCoreFixture>
{

}
